# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(489, 308)
        MainWindow.setStatusTip("")
        MainWindow.setAccessibleName("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 5, 81, 16))
        self.label.setObjectName("label")
        self.comboBox_settingname = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_settingname.setGeometry(QtCore.QRect(150, 68, 161, 22))
        self.comboBox_settingname.setObjectName("comboBox_settingname")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(150, 50, 81, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(150, 90, 71, 16))
        self.label_3.setObjectName("label_3")
        self.pushButton_pull = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_pull.setGeometry(QtCore.QRect(330, 130, 141, 28))
        self.pushButton_pull.setObjectName("pushButton_pull")
        self.lineEdit_gatestart = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_gatestart.setGeometry(QtCore.QRect(10, 230, 71, 22))
        self.lineEdit_gatestart.setObjectName("lineEdit_gatestart")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 210, 71, 16))
        self.label_5.setObjectName("label_5")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(-10, 190, 441, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.pushButton_start = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_start.setGeometry(QtCore.QRect(20, 140, 111, 28))
        self.pushButton_start.setObjectName("pushButton_start")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(30, 70, 81, 16))
        self.label_6.setObjectName("label_6")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(130, 0, 20, 211))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.pushButton_send = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_send.setGeometry(QtCore.QRect(330, 160, 141, 28))
        self.pushButton_send.setObjectName("pushButton_send")
        self.lineEdit_settingname = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_settingname.setGeometry(QtCore.QRect(330, 90, 141, 22))
        self.lineEdit_settingname.setObjectName("lineEdit_settingname")
        self.lineEdit_numframes = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_numframes.setGeometry(QtCore.QRect(170, 230, 71, 22))
        self.lineEdit_numframes.setObjectName("lineEdit_numframes")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(180, 210, 71, 16))
        self.label_8.setObjectName("label_8")
        self.lineEdit_gateend = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_gateend.setGeometry(QtCore.QRect(250, 230, 71, 22))
        self.lineEdit_gateend.setObjectName("lineEdit_gateend")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(260, 210, 71, 16))
        self.label_9.setObjectName("label_9")
        self.lineEdit_gatewidth = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_gatewidth.setGeometry(QtCore.QRect(90, 230, 71, 22))
        self.lineEdit_gatewidth.setObjectName("lineEdit_gatewidth")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(100, 210, 71, 16))
        self.label_10.setObjectName("label_10")
        self.pushButton_calcgate = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_calcgate.setGeometry(QtCore.QRect(360, 203, 91, 28))
        self.pushButton_calcgate.setObjectName("pushButton_calcgate")
        self.pushButton_updategate = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_updategate.setGeometry(QtCore.QRect(360, 233, 91, 28))
        self.pushButton_updategate.setObjectName("pushButton_updategate")
        self.pushButton_save = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_save.setGeometry(QtCore.QRect(410, 10, 51, 28))
        self.pushButton_save.setObjectName("pushButton_save")
        self.settings_elements = QtWidgets.QTextBrowser(self.centralwidget)
        self.settings_elements.setGeometry(QtCore.QRect(150, 110, 161, 81))
        self.settings_elements.setObjectName("settings_elements")
        self.comboBox_exp1 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_exp1.setGeometry(QtCore.QRect(10, 20, 121, 22))
        self.comboBox_exp1.setObjectName("comboBox_exp1")
        self.comboBox_exp2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_exp2.setGeometry(QtCore.QRect(10, 90, 121, 22))
        self.comboBox_exp2.setObjectName("comboBox_exp2")
        self.checkBox_logfileexp1 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_logfileexp1.setGeometry(QtCore.QRect(32, 46, 81, 20))
        self.checkBox_logfileexp1.setObjectName("checkBox_logfileexp1")
        self.checkBox_logfileexp2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_logfileexp2.setGeometry(QtCore.QRect(30, 115, 81, 20))
        self.checkBox_logfileexp2.setObjectName("checkBox_logfileexp2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(0, 260, 481, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.radioButton_contacq_exp2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_contacq_exp2.setGeometry(QtCore.QRect(230, 270, 171, 20))
        self.radioButton_contacq_exp2.setAutoExclusive(False)
        self.radioButton_contacq_exp2.setObjectName("radioButton_contacq_exp2")
        self.pushButton_load = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_load.setGeometry(QtCore.QRect(340, 10, 61, 28))
        self.pushButton_load.setObjectName("pushButton_load")
        self.pushButton_newsetting = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_newsetting.setGeometry(QtCore.QRect(350, 60, 101, 28))
        self.pushButton_newsetting.setObjectName("pushButton_newsetting")
        self.comboBox_expname = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_expname.setGeometry(QtCore.QRect(150, 21, 161, 22))
        self.comboBox_expname.setObjectName("comboBox_expname")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(150, 3, 81, 16))
        self.label_4.setObjectName("label_4")
        self.radioButton_contacq_exp1 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_contacq_exp1.setGeometry(QtCore.QRect(20, 270, 161, 20))
        self.radioButton_contacq_exp1.setAutoExclusive(False)
        self.radioButton_contacq_exp1.setObjectName("radioButton_contacq_exp1")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionReload_ppr = QtWidgets.QAction(MainWindow)
        self.actionReload_ppr.setObjectName("actionReload_ppr")
        self.actionOpen_Eventlog = QtWidgets.QAction(MainWindow)
        self.actionOpen_Eventlog.setObjectName("actionOpen_Eventlog")
        self.actionToggle_Legend = QtWidgets.QAction(MainWindow)
        self.actionToggle_Legend.setObjectName("actionToggle_Legend")
        self.actionOpen_Cutting_Times = QtWidgets.QAction(MainWindow)
        self.actionOpen_Cutting_Times.setObjectName("actionOpen_Cutting_Times")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Lightfield Control"))
        self.label.setText(_translate("MainWindow", "Experiment 1"))
        self.label_2.setText(_translate("MainWindow", "Setting name"))
        self.label_3.setText(_translate("MainWindow", "Elements"))
        self.pushButton_pull.setText(_translate("MainWindow", "Pull from expt"))
        self.label_5.setText(_translate("MainWindow", "Gate Start"))
        self.pushButton_start.setText(_translate("MainWindow", "Start"))
        self.label_6.setText(_translate("MainWindow", "Experiment 2"))
        self.pushButton_send.setText(_translate("MainWindow", "Send to expt"))
        self.label_8.setText(_translate("MainWindow", "# Frames"))
        self.label_9.setText(_translate("MainWindow", "Gate End"))
        self.label_10.setText(_translate("MainWindow", "Gate Width"))
        self.pushButton_calcgate.setText(_translate("MainWindow", "Calculate"))
        self.pushButton_updategate.setText(_translate("MainWindow", "Update Setting"))
        self.pushButton_save.setText(_translate("MainWindow", "Save"))
        self.checkBox_logfileexp1.setText(_translate("MainWindow", "Logfile?"))
        self.checkBox_logfileexp2.setText(_translate("MainWindow", "Logfile?"))
        self.radioButton_contacq_exp2.setText(_translate("MainWindow", "Continuous Acquisition Exp 2"))
        self.pushButton_load.setText(_translate("MainWindow", "Load"))
        self.pushButton_newsetting.setText(_translate("MainWindow", "New Setting"))
        self.label_4.setText(_translate("MainWindow", "Experiment"))
        self.radioButton_contacq_exp1.setText(_translate("MainWindow", "Continuous Acquisition Exp 1"))
        self.actionOpen.setText(_translate("MainWindow", "Open Logfile"))
        self.actionReload_ppr.setText(_translate("MainWindow", "Reload PPR"))
        self.actionOpen_Eventlog.setText(_translate("MainWindow", "Open Eventlog"))
        self.actionToggle_Legend.setText(_translate("MainWindow", "Toggle Legend"))
        self.actionOpen_Cutting_Times.setText(_translate("MainWindow", "Open Cutting Times"))

